MENU, SECTION, AI_CLARIFYING = range(3)

(
    ADDING_FILM_TITLE,
    ADDING_FILM_COMMENT,
    ADDING_FILM_SASHA_RATING,
    ADDING_FILM_VOVA_RATING,
    ADDING_WISHLIST_TITLE,
    ADDING_WISHLIST_LINK,
    ADDING_WISHLIST_COMMENT,
    ADDING_LEISURE_TITLE,
    ADDING_LEISURE_COMMENT,
    ADDING_EVENT_TITLE,
    ADDING_EVENT_PLACE,
    ADDING_EVENT_DATE,
    ADDING_EVENT_TIME,
    ADDING_EVENT_END_DATE,
    ADDING_EVENT_END_TIME,
    ADDING_EVENT_LINK,
    EDITING_AFISHA_DATE,
    EDITING_AFISHA_TIME,
    ADDING_CALENDAR_EVENT_TITLE,
    ADDING_CALENDAR_EVENT_DATE,
    ADDING_CALENDAR_EVENT_START_TIME,
    ADDING_CALENDAR_EVENT_END_TIME,
    ADDING_CALENDAR_EVENT_COMMENT,
    EDITING_CALENDAR_DATE,
    EDITING_CALENDAR_TIME,
    ADDING_BACKLOG_TITLE,
    ADDING_BACKLOG_DESCRIPTION,
    PLACE_ADD_NAME,
    PLACE_ADD_LINK,
    PLACE_ADD_COMMENT,
    CITY_ADD_NAME,
    CITY_ADD_COUNTRY,
    CITY_PLACE_ADD_NAME,
    CITY_PLACE_ADD_LINK,
    CITY_PLACE_ADD_COMMENT,
    CITY_PLACE_VISIT_COMMENT,
    ADDING_SPARK_TITLE,
    ADDING_SPARK_DESCRIPTION,
    ADDING_TICKET_TITLE,
    ADDING_TICKET_DATE,
    ADDING_TICKET_TIME,
    ADDING_TICKET_PLACE_ROUTE,
    ADDING_TICKET_COMMENT,
    ADDING_TICKET_ATTACHMENTS,
    ADDING_PURCHASE_TITLE,
    ADDING_PURCHASE_LINK,
    ADDING_PURCHASE_PRICE,
    ADDING_PURCHASE_PRIORITY,
    ADDING_PURCHASE_COMMENT,
    EDITING_PURCHASE_FIELD,
) = range(10, 60)

# Films v2 metadata selection states. Keep the established state numbers above
# stable because older conversations may still be in flight during deployment.
SELECTING_FILM_METADATA, CONFIRMING_FILM_ADD = range(60, 62)

# Films v2 legacy metadata enrichment. Never renumber deployed states above.
(
    FILM_ENRICHMENT_REVIEW,
    FILM_ENRICHMENT_MANUAL_QUERY,
    FILM_ENRICHMENT_SELECTING,
    FILM_ENRICHMENT_CONFIRMING,
) = range(62, 66)

# Native event attachment flow. Never renumber deployed states above.
ADDING_EVENT_ATTACHMENT_FILE, SELECTING_EVENT_ATTACHMENT_TYPE, SELECTING_EVENT_ATTACHMENT_TRANSPORT = range(66, 69)

# NL/resumable event attachment flow. Never renumber deployed states above.
WAITING_FOR_NL_ATTACHMENTS, SELECTING_NL_ATTACHMENT_EVENT, CONFIRMING_NL_ATTACHMENT = range(69, 72)

# Exact-title fallback for the bounded orphan-file event chooser.
ENTERING_NL_ATTACHMENT_EVENT_TITLE = 72
