MENU, SECTION = range(2)

(
    ADDING_MOSCOW_PLACE_TITLE,
    ADDING_MOSCOW_PLACE_LINK,
    ADDING_MOSCOW_PLACE_COMMENT,
    ADDING_CITY_TITLE,
    ADDING_CITY_COUNTRY,
    ADDING_CITY_PLACE_TITLE,
    ADDING_CITY_PLACE_LINK,
    ADDING_CITY_PLACE_COMMENT,
    ADDING_CITY_PLACE_VISITED_COMMENT,
) = range(100, 109)
